version: '3'
services:
  front:
    container_name: front
    hostname: front
    build:
      context: ./front
      dockerfile: dev.dockerfile
    volumes:
      - ./front:/usr/front
      - /usr/front/node_modules
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development