version: '3'

volumes:
  logs:
    driver: local
  dbdata:
    driver: local

services:
  back:
    build:
      context: ./back
      dockerfile: dev.dockerfile
    container_name: back
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - ./back:/var/www
      - logs:/var/www/logs
    networks:
      - my-network

  front:
    container_name: front
    hostname: front
    build:
      context: ./front
      dockerfile: dev.dockerfile
    volumes:
      - ./front:/usr/src/app/
      - ./front/node_modules:/usr/src/app/node_modules
      #- /usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '3003:3003'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - my-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - my-network

networks:
  my-network:
    driver: bridge