version: '3'

volumes:
  logs:
    driver: local

services:
  back:
    image: php:7-alpine
    container_name: back
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - ./back:/var/www
      - logs:/var/www/logs
    networks:
      - my-network

  front:
    container_name: front
    hostname: front
    build:
      context: ./front
      dockerfile: dev.dockerfile
    volumes:
      - ./front:/usr/src/app/
      - ./front/node_modules:/usr/src/app/node_modules
      #- /usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '3003:3003'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - my-network

networks:
  my-network:
    driver: bridge